# Generated by Django 4.2 on 2023-05-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Angelwing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emailController", models.EmailField(max_length=100, unique=True)),
                ("pwdController", models.CharField(max_length=80, unique=True)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="outsiders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unameController", models.CharField(max_length=100, unique=True)),
                ("addressController", models.CharField(max_length=100, unique=True)),
                ("contactController", models.CharField(max_length=100)),
                ("emailController", models.EmailField(max_length=100, unique=True)),
                ("pwdController", models.CharField(max_length=80, unique=True)),
                ("cpwdController", models.CharField(max_length=80, unique=True)),
                ("role", models.CharField(max_length=10)),
                ("userstatus", models.CharField(max_length=10)),
                (
                    "userimage",
                    models.ImageField(max_length=500, null=True, upload_to="images"),
                ),
                (
                    "log_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Outsiders.log"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="money_donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amountController", models.CharField(max_length=100)),
                ("money_dateInput", models.DateField()),
                ("md_status", models.CharField(max_length=40)),
                (
                    "orphlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Angelwing.orphanage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsiders.outsiders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="food_donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fd_type", models.CharField(max_length=100)),
                ("fd_dateInput", models.DateField()),
                ("quantityController", models.CharField(max_length=100)),
                ("fd_status", models.CharField(max_length=50)),
                (
                    "orphlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Angelwing.orphanage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsiders.outsiders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=100)),
                ("feedback_status", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsiders.outsiders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cloth_donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=50)),
                ("sizeController", models.CharField(max_length=50)),
                ("quantityController", models.CharField(max_length=50)),
                ("cloth_dateInput", models.DateField()),
                ("cd_status", models.CharField(max_length=50)),
                (
                    "orphlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Angelwing.orphanage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsiders.outsiders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="adoption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("adp_status", models.CharField(max_length=50)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Angelwing.orphan",
                    ),
                ),
                (
                    "orphlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Angelwing.orphanage",
                    ),
                ),
                (
                    "outsider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsiders.outsiders",
                    ),
                ),
            ],
        ),
    ]
