# Generated by Django 4.2 on 2023-05-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Angelwing", "0001_initial"),
        ("Outsiders", "0002_delete_money_donation"),
    ]

    operations = [
        migrations.CreateModel(
            name="money_donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amountController", models.CharField(max_length=100)),
                ("money_dateInput", models.DateField()),
                ("md_status", models.CharField(max_length=40)),
                (
                    "orphlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Angelwing.orphanage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsiders.outsiders",
                    ),
                ),
            ],
        ),
    ]
