# Generated by Django 4.2 on 2023-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Outsiders", "0003_money_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="money_donation",
            name="pmtmethod",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
