# Generated by Django 4.2 on 2023-06-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Outsiders", "0004_money_donation_pmtmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="adp_status",
            field=models.CharField(default="0", max_length=50),
        ),
    ]
