# Generated by Django 4.2 on 2023-06-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Outsiders", "0005_alter_adoption_adp_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="forgetPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emailController", models.EmailField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Outsiders.log"
                    ),
                ),
            ],
        ),
    ]
