# Generated by Django 4.2 on 2023-06-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Outsiders", "0006_forgetpassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outsiders",
            name="userimage",
            field=models.ImageField(
                default="/meadia/images/user1.png", max_length=500, upload_to="images"
            ),
        ),
    ]
