# Generated by Django 4.2 on 2023-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Outsiders", "0009_adoptionform_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adoptionform",
            name="status",
        ),
        migrations.AddField(
            model_name="adoptionform",
            name="personal_status",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
