# Generated by Django 4.2 on 2023-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Outsiders", "0010_remove_adoptionform_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionform",
            name="gender",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
