# Generated by Django 4.2 on 2023-06-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Outsiders", "0011_adoptionform_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forgetpassword",
            name="user",
        ),
    ]
