# Generated by Django 4.2 on 2023-05-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="schemes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme_name", models.CharField(max_length=100)),
                ("eligibility", models.CharField(max_length=500)),
                ("last_date", models.DateField()),
                ("applin_link", models.CharField(max_length=100)),
                ("scheme_status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_title", models.CharField(max_length=150)),
                ("rule_content", models.CharField(max_length=500)),
                ("rule_date", models.DateField()),
                ("rule_status", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="outsiders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_address", models.CharField(max_length=500)),
                ("user_email", models.EmailField(max_length=200)),
                ("user_status", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="orphanage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orphanage_name", models.CharField(max_length=100)),
                ("orphanage_address", models.CharField(max_length=500)),
                ("orphanage_contact", models.CharField(max_length=50)),
                ("orphanage_description", models.CharField(max_length=500)),
                ("orphanage_email", models.EmailField(max_length=200)),
                (
                    "orphanage_image",
                    models.ImageField(max_length=500, upload_to="images"),
                ),
                ("status", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="orphan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orphan_name", models.CharField(max_length=200)),
                ("orphan_age", models.CharField(max_length=150)),
                (
                    "orphan_gender",
                    models.CharField(
                        choices=[("female", "Female"), ("male", "Male")], max_length=100
                    ),
                ),
                ("orphan_dob", models.DateField()),
                ("orphan_address", models.CharField(max_length=200)),
                (
                    "orphan_blood",
                    models.CharField(
                        choices=[
                            ("a+", "A+"),
                            ("b+", "B+"),
                            ("ab+", "AB+"),
                            ("o+", "O+"),
                            ("a-", "A-"),
                            ("b-", "B-"),
                            ("ab-", "AB-"),
                            ("o-", "O-"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "orphan_hobbies",
                    models.CharField(
                        choices=[
                            ("writing", "Writing"),
                            ("reading", "Reading"),
                            ("singing", "Singing"),
                            ("dancing", "Dancing"),
                            ("drawing", "Drawing"),
                        ],
                        max_length=100,
                    ),
                ),
                ("orphan_image", models.ImageField(max_length=500, upload_to="images")),
                ("orphan_status", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Angelwing.orphanage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_title", models.CharField(max_length=150)),
                ("notification_content", models.CharField(max_length=500)),
                ("notification_date", models.DateField()),
                ("notification_status", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=200)),
                ("event_content", models.CharField(max_length=500)),
                ("event_place", models.CharField(max_length=200)),
                ("event_date", models.DateField()),
                ("event_time", models.CharField(max_length=150)),
                ("event_status", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_title", models.CharField(max_length=150)),
                ("blog_content", models.CharField(max_length=500)),
                ("blog_date", models.DateField()),
                ("blog_image", models.ImageField(max_length=500, upload_to="images")),
                ("blog_status", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
