# Generated by Django 4.2 on 2023-06-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Outsiders", "0010_remove_adoptionform_status_and_more"),
        ("Angelwing", "0003_adoption_notify"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption_notify",
            name="outsider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Outsiders.adoptionform"
            ),
        ),
    ]
