# Generated by Django 4.2 on 2023-06-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Angelwing", "0004_alter_adoption_notify_outsider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adoption_notify",
            old_name="outsider",
            new_name="adoptionforms",
        ),
    ]
