# Generated by Django 4.2 on 2023-06-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Angelwing", "0005_rename_outsider_adoption_notify_adoptionforms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemes",
            name="applin_link",
            field=models.URLField(),
        ),
    ]
